// Auto-generated by tools/gen_i18n.py - DO NOT EDIT
#pragma once

#include <stdint.h>

// Available languages
typedef enum {
    LANG_EN,
    LANG_DE,
    LANG_COUNT
} language_t;

// String IDs
typedef enum {
    STR_MAIN_MENU,
    STR_SETTINGS,
    STR_BADGE_TEXTS,
    STR_TOTP_CODES,
    STR_PASSWORDS,
    STR_FIDO2_KEYS,
    STR_SYSTEM_TEST,
    STR_SLEEP,
    STR_CHANGE_PIN,
    STR_BRIGHTNESS,
    STR_SET_DATE,
    STR_SET_TIME,
    STR_SET_DATETIME,
    STR_LANGUAGE,
    STR_BACK,
    STR_NAME,
    STR_INFO,
    STR_INFO2,
    STR_ENTER_PIN,
    STR_CURRENT_PIN,
    STR_NEW_PIN,
    STR_CONFIRM_PIN,
    STR_UNLOCK,
    STR_PRESS_ANY_KEY,
    STR_DATE,
    STR_TIME,
    STR_SAVED,
    STR_UNLOCKED,
    STR_WRONG_PIN,
    STR_LOCKED_OUT,
    STR_PINS_DONT_MATCH,
    STR_PIN_CHANGED,
    STR_DELETED,
    STR_DELETE_FAILED,
    STR_USB_NOT_READY,
    STR_CODE_TYPED,
    STR_PASSWORD_TYPED,
    STR_NO_ACCOUNTS,
    STR_NO_KEYS,
    STR_UNPLUG_USB,
    STR_TIME_NOT_SYNCED,
    STR_DATE_SAVED,
    STR_TIME_SAVED,
    STR_TOO_MANY_ATTEMPTS,
    STR_SAVE_FAILED,
    STR_SELECT,
    STR_EDIT,
    STR_DELETE,
    STR_CANCEL,
    STR_APPROVE,
    STR_DENY,
    STR_OK,
    STR_TOTP_CODE,
    STR_PASSWORD_DETAIL,
    STR_FIDO2_REQUEST,
    STR_FIDO2_DETAIL,
    STR_REGISTER_KEY,
    STR_SIGN_IN,
    STR_USE_DEVICE,
    STR_SHOW_CODE,
    STR_TYPE_CODE,
    STR_BADGE_NAME,
    STR_BADGE_INFO,
    STR_BADGE_INFO2,
    STR_HINT_TYPE_BACK,
    STR_HINT_TOTP_CODE,
    STR_HINT_PASS_DETAIL,
    STR_HINT_DELETE_BACK,
    STR_HINT_APPROVE_DENY,
    STR_HINT_BRIGHTNESS,
    STR_HINT_T9_INPUT,
    STR_HINT_PIN_INPUT,
    STR_HINT_DATE_TIME,
    STR_HINT_IP_INPUT,
    STR_HINT_BACK,
    STR_HINT_SELECT,
    STR_HINT_LIST_MENU,     // "[3] Menu"

    // Tools Menu
    STR_TOOLS,              // "Tools"
    STR_NTP_SYNC,           // "NTP Sync"
    STR_NTP_SYNCING,        // "Syncing time..."
    STR_NTP_SUCCESS,        // "Time synced!"
    STR_NTP_FAILED,         // "NTP sync failed"
    STR_TIMEOUT,            // "Timeout"

    // WiFi
    STR_WIFI_MENU,          // "WiFi"
    STR_WIFI_SETUP,         // "WiFi Setup"
    STR_WIFI_CONNECT,       // "Connect"
    STR_WIFI_DETAILS,       // "Details"
    STR_WIFI_DISCONNECT,    // "Disconnect"
    STR_WIFI_DISCONNECTED,  // "Disconnected"
    STR_WIFI_NO_CONFIG,     // "No WiFi configured"
    STR_WIFI_SCANNING,      // "Scanning..."
    STR_WIFI_NO_NETWORKS,   // "No networks"
    STR_WIFI_PASSWORD,      // "Password"
    STR_WIFI_ENCRYPTION,    // "Encryption"
    STR_WIFI_IP_MODE,       // "IP Mode"
    STR_WIFI_DHCP,          // "DHCP (Auto)"
    STR_WIFI_STATIC,        // "Static IP"
    STR_WIFI_GATEWAY,       // "Gateway"
    STR_WIFI_NETMASK,       // "Netmask"
    STR_WIFI_CONNECTING,    // "Connecting..."
    STR_WIFI_CONNECTED,     // "Connected!"
    STR_WIFI_FAILED,        // "Connection failed"
    STR_WIFI_SAVED_IP,      // "Last IP"
    STR_WIFI_ADD_MANUAL,    // "Add Manual"
    STR_WIFI_SSID,          // "SSID"

    // Settings
    STR_TIMEZONE,           // "Timezone"

    // Bluetooth
    STR_BLUETOOTH_ON,       // "Bluetooth ON"
    STR_BLUETOOTH_OFF,      // "Bluetooth OFF"
    STR_BLUETOOTH_AUTO_OFF, // "BLE Auto-Off"
    STR_BLUETOOTH_DISABLE_WIFI, // "Disable WiFi first"
    STR_WIFI_DISABLE_BLUETOOTH, // "Disable Bluetooth first"

    // Certificate Authority (CA)
    STR_CA_MENU,            // "CA Management"
    STR_CA_STATUS,          // "CA Status"
    STR_CA_GENERATE,        // "Generate Root CA"
    STR_CA_IMPORT,          // "Import Root CA"
    STR_CA_EXPORT,          // "Export Root CA"
    STR_CA_SIGN_CSR,        // "Sign CSR"
    STR_CA_NOT_INIT,        // "CA not initialized"
    STR_CA_INITIALIZED,     // "CA initialized"
    STR_CA_GENERATING,      // "Generating..."
    STR_CA_GENERATED,       // "CA generated!"
    STR_CA_GENERATE_FAILED, // "Generation failed"
    STR_CA_COMMON_NAME,     // "Common Name"
    STR_CA_CREATED,         // "Created"
    STR_CA_VALID_UNTIL,     // "Valid until"
    STR_CA_ISSUED_CERTS,    // "Issued certs"
    STR_CA_SERIAL,          // "Next serial"
    STR_CA_SHOW_QR,         // "Show QR Code"
    STR_CA_QR_PUBKEY,       // "CA Public Key"
    STR_CA_RESET,           // "Reset Root CA"
    STR_CA_RESET_CONFIRM,   // "Delete CA? Y=Yes N=No"
    STR_CA_RESET_SUCCESS,   // "CA deleted"
    // CA Wizard
    STR_CA_ENTER_CN,        // "Common Name (CN)"
    STR_CA_ENTER_ORG,       // "Organization (O)"
    STR_CA_ENTER_OU,        // "Org. Unit (OU)"
    STR_CA_ENTER_COUNTRY,   // "Country (C)"
    STR_CA_ENTER_LOCALITY,  // "City/Locality (L)"
    STR_CA_ENTER_STATE,     // "State/Province (ST)"
    STR_CA_VALIDITY_YEARS,  // "Validity (Years)"

    // Remote Badge / BLE Badge
    STR_BLUETOOTH,          // "Bluetooth"
    STR_REMOTE_BADGE,       // "Remote Badge" (Main menu entry)
    STR_VCARDS,             // "vCards" (Submenu)
    STR_VCARD_ADD,          // "Add"
    STR_VCARD_LIST,         // "Cards"
    STR_VCARD_BROADCAST,    // "Broadcast" (Submenu)
    STR_VCARD_SCAN,         // "Scan"
    STR_BROADCAST_SETTINGS, // "Settings" (Submenu)
    STR_BEACON_SEND,        // "Beacon Send"
    STR_BEACON_RECEIVE,     // "Beacon Receive"
    STR_VCARD_ADV_INTERVAL, // "Send Interval"
    STR_VCARD_SCAN_INTERVAL,// "Scan Interval"
    STR_TX_POWER,           // "TX Power"
    STR_VCARD_RECEIVE,      // "Receive"
    STR_VCARD_EXCHANGE,     // "Exchange"
    STR_VCARD_EXCHANGE_MSG, // "Scanning for badges..."
    STR_VCARD_SEND,         // "Send"
    STR_VCARD_SHOW_QR,      // "Show QR"
    STR_VCARD_NEARBY,       // "Nearby: %s"
    STR_VCARD_NEARBY_TITLE, // "Nearby"
    STR_VCARD_SENDING,      // "Sending vCard..."
    STR_VCARD_SEND_SUCCESS, // "Transfer complete"
    STR_VCARD_SEND_FAILED,  // "Transfer failed"
    STR_VCARD_ENABLE_EXCHANGE, // "Enable exchange mode"
    STR_VCARD_NEARBY_LIST,  // "Nearby Badges"
    STR_NO_BADGES,          // "No badges"
    STR_VCARD_QR,           // "QR vCard"
    STR_ON,                 // "On"
    STR_OFF,                // "Off"
    STR_VIEW,               // "View"
    STR_NO_VCARDS,          // "No vCards"
    STR_MY_VCARD,           // "My vCard"
    STR_FIRST_NAME,         // "First name"
    STR_LAST_NAME,          // "Last name"
    STR_DESCRIPTION,        // "Description"
    STR_PHONE,              // "Phone" (category)
    STR_PHONE_LANDLINE,     // "Landline"
    STR_PHONE_MOBILE,       // "Mobile"
    STR_PHONE_BUSINESS,     // "Business"
    STR_PHONE_PAGER,        // "Pager"
    STR_EMAIL,              // "Email"
    STR_URL,                // "URL"
    STR_ORG,                // "Organization"
    STR_TITLE,              // "Title"
    STR_SOCIAL,             // "Social"
    STR_IMPP,               // "Messenger" (category)
    STR_IMPP_TELEGRAM,      // "Telegram"
    STR_IMPP_SIGNAL,        // "Signal"
    STR_IMPP_WHATSAPP,      // "WhatsApp"
    STR_IMPP_DISCORD,       // "Discord"
    STR_IMPP_MATRIX,        // "Matrix"
    STR_IMPP_THREEMA,       // "Threema"
    STR_IMPP_OTHER,         // "Other"
    STR_ADDRESS,            // "Address" (category)
    STR_ADDRESS_HOME,       // "Home"
    STR_ADDRESS_WORK,       // "Work"
    STR_SAVE,               // "Save"
    STR_PAIRING,            // "Pairing"
    STR_PAIRING_CONFIRM,    // "Confirm code: %06lu"
    STR_PAIRING_DISPLAY,    // "Enter on other device: %06lu"
    STR_PAIRING_PIN,        // "Enter Passkey"
    STR_PAIRING_PIN_MSG,    // "Enter code from other device"

    STR_VCARD_TOO_BIG,      // "vCard too big"

    STR_COUNT
} string_id_t;

// Initialize i18n module (loads language from NVS)
void i18n_init(void);

// Get/set current language
language_t i18n_get_language(void);
void i18n_set_language(language_t lang);

// Get translated string
const char* i18n_str(string_id_t id);

// Get language name (for display)
const char* i18n_get_language_name(language_t lang);
